spring:
  application:
    name: gateway
server:
  port: 10000

sidecar:
  port: 8000

eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/